// Generated by cra-context-generator@1.4.0 on Mon, 06 Feb 2023 14:42:10 GMT.
// Do not edit this file manually unless you disabled its code generation.
import React from 'react';

/**
 * The App state props interface.
 */
export interface IAppStateProps {
    language?: string;
    num: number;
    theme?: string;
}

/**
 * The App state interface.
 */
export interface IAppState {
    languageState?: string;
    setLanguageState?: React.Dispatch<React.SetStateAction<string | undefined>>;
    numState: number;
    setNumState?: React.Dispatch<React.SetStateAction<number>>;
    themeState?: string;
    setThemeState?: React.Dispatch<React.SetStateAction<string | undefined>>;
}

/**
 * The App context provider props interface.
 */
export interface IAppContextProviderProps {
    children: React.ReactNode;
    appState: IAppState;
    languageSetEventHandler?: (language?: string) => void;
    numSetEventHandler?: (num: number) => void;
    themeSetEventHandler?: (theme?: string) => void;
}

/**
 * The App context value interface.
 */
export interface IAppContextValue {
    language?: string;
    setLanguage: (language?: string) => void;
    num: number;
    setNum: (num: number) => void;
    theme?: string;
    setTheme: (theme?: string) => void;
}

export const DefaultLanguage = 'en';
export const DefaultNum = 0;
export const DefaultTheme = 'default';

/**
 * The default App state.
 */
export const DefaultAppState: IAppState = {
    languageState: DefaultLanguage,
    setLanguageState: undefined,
    numState: DefaultNum,
    setNumState: undefined,
    themeState: DefaultTheme,
    setThemeState: undefined,
};

/**
 * The default App context value.
 */
export const DefaultAppContextValue: IAppContextValue = {
    language: DefaultLanguage,
    setLanguage: (language?: string) => {},
    num: DefaultNum,
    setNum: (num: number) => {},
    theme: DefaultTheme,
    setTheme: (theme?: string) => {},
};

/**
 * The App state.
 */
export const AppState = ({
            language,
            num,
            theme,
        }: IAppStateProps) => {

    const [ languageState, setLanguageState ] = React.useState<string | undefined>(language || DefaultLanguage);
    const [ numState, setNumState ] = React.useState<number>(num || DefaultNum);
    const [ themeState, setThemeState ] = React.useState<string | undefined>(theme || DefaultTheme);

    const appState: IAppState = {
        languageState,
        setLanguageState,
        numState,
        setNumState,
        themeState,
        setThemeState,
    };

    return appState;
};

/**
 * The App context.
 * The DefaultAppContextValue argument is only used when a component does not have a matching Provider above it in the tree.
 * This can be helpful for testing components.
 */
export const AppContext = React.createContext<IAppContextValue>(DefaultAppContextValue);

/**
 * The App context provider.
 */
export const AppContextProvider = ({
            children,
            appState,
            languageSetEventHandler,
            numSetEventHandler,
            themeSetEventHandler,
        }: IAppContextProviderProps) => {

    const {
        languageState,
        setLanguageState,
        numState,
        setNumState,
        themeState,
        setThemeState,
    } = appState || {};

    React.useEffect(() => {
        languageSetEventHandler && languageSetEventHandler(languageState);
    }, [ languageState, setLanguageState, languageSetEventHandler ]);

    React.useEffect(() => {
        numSetEventHandler && numSetEventHandler(numState);
    }, [ numState, setNumState, numSetEventHandler ]);

    React.useEffect(() => {
        themeSetEventHandler && themeSetEventHandler(themeState);
    }, [ themeState, setThemeState, themeSetEventHandler ]);

    const contextValue: IAppContextValue = {
        language: languageState,
        setLanguage: (language?: string) => setLanguageState && setLanguageState(language),
        num: numState,
        setNum: (num: number) => setNumState && setNumState(num),
        theme: themeState,
        setTheme: (theme?: string) => setThemeState && setThemeState(theme),
    };

    return (
        <AppContext.Provider value={contextValue}>
            {children}
        </AppContext.Provider>
    );
};
